Coach fitz debug
ligerbots/InfiniteRecharge2020 pull request #40
Opened 2020-11-28 22:43 UTC by coachFitz0807

It's probably time to merge this to InfiniteSimulator. I merged fix_startup_jump and the new fieldmap with the shield generator to CoachFitzDebug.

2020-11-28 23:29 UTC, LQ1234 approved these changes
Looks good to me

2020-11-29 01:31 UTC, prensing commented
@coachFitz0807 The 3 commands all to "driveTrain.setPose(initialPose)" at the start. However, I think that is redundant. The Robot will already have done that many times in Robot.disabledPeriodic().  Do you think that is needed in the commands?

2020-11-29 01:33 UTC, prensing commented
Actually, yes, it is in the constructor of each, so actually is a bad idea. As each command is constructed while building the SendableChooser, the robot will jump around the field (unnecessarily).

2020-11-29 01:42 UTC, prensing requested changes

2020-11-29 01:42 UTC, prensing commented on src/main/java/frc/robot/commands/NewEightBallSim.java
> +        robotDrive.setPose(initialPose);
I think this should be removed

2020-11-29 01:42 UTC, prensing commented on src/main/java/frc/robot/commands/ShedTest.java
> +        robotDrive.setPose(initialPose);
This should be removed.

2020-11-29 01:42 UTC, prensing commented on src/main/java/frc/robot/commands/TrenchAuto.java
> +        robotDrive.setPose(initialPose);
This should be removed.

2020-11-29 01:49 UTC, YJ-7274 approved these changes
Everything looks good besides the changes that coach Rensing brought up.

2020-11-29 02:00 UTC, coachFitz0807 commented on src/main/java/frc/robot/commands/NewEightBallSim.java
> +        robotDrive.setPose(initialPose);
I concur.

2020-11-29 02:00 UTC, coachFitz0807 commented on src/main/java/frc/robot/commands/ShedTest.java
> +        robotDrive.setPose(initialPose);
I concur

2020-11-29 02:00 UTC, coachFitz0807 commented on src/main/java/frc/robot/commands/TrenchAuto.java
> +        robotDrive.setPose(initialPose);
I concur.

2020-11-29 02:21 UTC, coachFitz0807 reviewed
Implemented changes suggested by Coach Rensing.

2020-11-29 02:29 UTC, prensing approved these changes

2020-11-29 16:14 UTC, merged